// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int64) error
	// User queries for example app (SQLite)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserExistsByEmail(ctx context.Context, email string) (int64, error)
	UserExistsByEmailExcluding(ctx context.Context, arg UserExistsByEmailExcludingParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
