// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersStmt, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, birthdate, created_at, updated_at)
VALUES (?, ?, ?, datetime('now'), datetime('now'))
RETURNING id, name, email, password, birthdate, created_at, updated_at
`

type CreateUserParams struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Birthdate string `json:"birthdate"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Name, arg.Email, arg.Birthdate)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, name, email, password, birthdate, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

// User queries for example app (SQLite)
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, birthdate, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, birthdate, created_at, updated_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Birthdate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = ?, email = ?, birthdate = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, email, password, birthdate, created_at, updated_at
`

type UpdateUserParams struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Birthdate string `json:"birthdate"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.Name,
		arg.Email,
		arg.Birthdate,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ?)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (int64, error) {
	row := q.queryRow(ctx, q.userExistsByEmailStmt, userExistsByEmail, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const userExistsByEmailExcluding = `-- name: UserExistsByEmailExcluding :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = ? AND id != ?)
`

type UserExistsByEmailExcludingParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UserExistsByEmailExcluding(ctx context.Context, arg UserExistsByEmailExcludingParams) (int64, error) {
	row := q.queryRow(ctx, q.userExistsByEmailExcludingStmt, userExistsByEmailExcluding, arg.Email, arg.ID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
